Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box_download_insecure = true    
      master.vm.box = "generic/ubuntu2204"
      master.vm.network "private_network", ip: "100.0.0.100"
      master.vm.hostname = "master"
      master.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
    config.vm.define "node1" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.2"
      worker.vm.hostname = "node1"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node2" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.3"
      worker.vm.hostname = "node2"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node3" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.4"
      worker.vm.hostname = "node3"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node4" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.5"
      worker.vm.hostname = "node4"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node5" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.6"
      worker.vm.hostname = "node5"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node6" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.7"
      worker.vm.hostname = "node6"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node7" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.8"
      worker.vm.hostname = "node7"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node8" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.9"
      worker.vm.hostname = "node8"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node9" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.10"
      worker.vm.hostname = "node9"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node10" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.11"
      worker.vm.hostname = "node10"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node11" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.12"
      worker.vm.hostname = "node11"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
    config.vm.define "node12" do |worker|
      worker.vm.box_download_insecure = true 
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.network "private_network", ip: "100.0.0.13"
      worker.vm.hostname = "node12"
      worker.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
  
  end
  